### ISSUE TITLE
Tracking bug for working pseudocode interpreter

### ISSUE THREAD

**Issue by veluca93** [algorithm-ninja/pseudocode-interpreter#1]
Necessary: 
- [x] Add support for min, max, repeat as new expressions.
- [x] Add support for reading input as new expressions.
- [ ] i10n of error messages
- [x] Better output format (do not use Debug)
- [x] Error out with empty arrays
- [x] Web editor
- [ ] Web debugger

Useful:
- [x] Add integration with terry
- [ ] intrinsic "error", "debugger break" to populate debugger timeline
- [ ] Getting started guide
- [ ] Add support for builtin functions and methods
- [ ] Make special expressions built-ins instead
- [ ] Add support for generics

Maybe: 
- [ ] block editor
